"""Runtime configuration, read from environment (see .env.example)."""

from __future__ import annotations

from pathlib import Path

from pydantic import AliasChoices, Field
from pydantic_settings import BaseSettings, SettingsConfigDict

_BACKEND_DIR = Path(__file__).resolve().parents[2]
_REPO_ROOT = _BACKEND_DIR.parent


class Settings(BaseSettings):
    # Absolute paths, because commands run from both the repo root and
    # backend/ and a relative env_file would silently resolve to neither.
    # Later files win: `.env.local` is machine-generated by `neon link` and
    # `neon deploy`, and backend/.env is hand-maintained, so a local override
    # beats the pulled value.
    model_config = SettingsConfigDict(
        env_file=(_REPO_ROOT / ".env.local", _BACKEND_DIR / ".env"),
        env_prefix="MACROMATE_",
        extra="ignore",
    )

    port: int = 8080
    log_level: str = "INFO"

    # See .env.example for why these two matter in deployment.
    mcp_stateless: bool = False
    allowed_hosts: str = "127.0.0.1,localhost"

    bedrock_model_id: str = "us.anthropic.claude-sonnet-4-5-20250929-v1:0"

    # Nutrition data sources.
    # Never hardcode a real key here -- this file is committed to a public repo.
    # Set MACROMATE_USDA_API_KEY in .env (gitignored). Required for Task 7; the
    # stubbed search_nutrition works without it.
    usda_api_key: str = ""

    # Database.
    # Accepts the bare DATABASE_URL that `neon link` writes to .env.local, as
    # well as the prefixed form, so there is no need to copy the credential
    # into a second file where it can go stale when Neon rotates it.
    database_url: str = Field(
        default="postgresql+asyncpg://postgres:postgres@localhost:5432/macromate",
        validation_alias=AliasChoices("MACROMATE_DATABASE_URL", "DATABASE_URL"),
    )
    # Neon's pooled endpoint is PgBouncer in transaction mode, which does not
    # support the session-level state DDL needs. Migrations use the direct
    # endpoint when one is available.
    database_url_unpooled: str = Field(
        default="",
        validation_alias=AliasChoices(
            "MACROMATE_DATABASE_URL_UNPOOLED", "DATABASE_URL_UNPOOLED"
        ),
    )

    # OAuth (Alexa+ account-linking — required before add-on deployment)
    oauth_client_id: str = "macromate-alexa"
    oauth_client_secret: str = ""
    oauth_issuer: str = ""  # Set to your App Runner URL before deploying

    @property
    def allowed_host_list(self) -> list[str]:
        return [h.strip() for h in self.allowed_hosts.split(",") if h.strip()]

    @property
    def migration_database_url(self) -> str:
        """Direct (unpooled) URL when available -- see `database_url_unpooled`."""
        return self.database_url_unpooled or self.database_url


settings = Settings()
