"""Initial schema for the MVP cooking flow.

Hand-written rather than autogenerated, for two reasons:

1. The unique partial index on `meal_logs(portion_id) WHERE voided = false`
   is required by REQ-6.4 and Alembic does not autogenerate partial indexes.
2. `item_state` is used by three tables. Left to `sa.Enum` inline, Alembic
   would emit CREATE TYPE once per table and the second one would fail, so
   the enum types are created explicitly up front and referenced with
   `create_type=False`.

Revision ID: 0001
Revises:
Create Date: 2026-09-18

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# create_type=False: these are created once, explicitly, in upgrade().
item_state = postgresql.ENUM(
    "AVAILABLE", "PREPARED", "CONSUMED", name="item_state", create_type=False
)
session_status = postgresql.ENUM(
    "ACTIVE", "FINALIZED", "ABANDONED", name="session_status", create_type=False
)
nutrition_source = postgresql.ENUM(
    "USDA", "OPENFOODFACTS", "USER_LABEL", "ESTIMATED", name="nutrition_source", create_type=False
)

UUID_DEFAULT = sa.text("uuid_generate_v4()")


def upgrade() -> None:
    # Required by the uuid_generate_v4() column defaults.
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')

    bind = op.get_bind()
    item_state.create(bind, checkfirst=True)
    session_status.create(bind, checkfirst=True)
    nutrition_source.create(bind, checkfirst=True)

    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=UUID_DEFAULT),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )

    op.create_table(
        "profiles",
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column("calorie_target", sa.Float(), nullable=False),
        sa.Column("protein_target_g", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )

    op.create_table(
        "equipment",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=UUID_DEFAULT),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_equipment_user_id", "equipment", ["user_id"])

    op.create_table(
        "preferences",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=UUID_DEFAULT),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_preferences_user_id", "preferences", ["user_id"])

    op.create_table(
        "pantry_items",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=UUID_DEFAULT),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("quantity_g", sa.Float(), nullable=False),
        sa.Column("calories_per_100g", sa.Float(), nullable=False),
        sa.Column("protein_g_per_100g", sa.Float(), nullable=False),
        sa.Column("nutrition_source", nutrition_source, nullable=False),
        sa.Column("estimated", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("state", item_state, nullable=False, server_default="AVAILABLE"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_pantry_items_user_id", "pantry_items", ["user_id"])

    op.create_table(
        "cooking_sessions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=UUID_DEFAULT),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("status", session_status, nullable=False, server_default="ACTIVE"),
        # NULL means "no override, fall back to the saved list". An empty array
        # means "explicitly nothing". They are not the same.
        sa.Column("equipment_override", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("preference_overrides", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_cooking_sessions_user_id", "cooking_sessions", ["user_id"])

    op.create_table(
        "session_ingredients",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=UUID_DEFAULT),
        sa.Column(
            "session_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("cooking_sessions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "pantry_item_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("pantry_items.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("quantity_g", sa.Float(), nullable=False),
        sa.Column("calories", sa.Float(), nullable=False),
        sa.Column("protein_g", sa.Float(), nullable=False),
        sa.Column("estimated", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("state", item_state, nullable=False, server_default="AVAILABLE"),
        sa.Column("correction_factor", sa.Float(), nullable=False, server_default=sa.text("1.0")),
    )
    op.create_index("ix_session_ingredients_session_id", "session_ingredients", ["session_id"])

    op.create_table(
        "recipe_batches",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=UUID_DEFAULT),
        sa.Column(
            "session_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("cooking_sessions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("total_calories", sa.Float(), nullable=False),
        sa.Column("total_protein_g", sa.Float(), nullable=False),
        sa.Column("estimated", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("portions_intended", sa.Integer(), nullable=False),
        sa.Column("calories_per_portion", sa.Float(), nullable=False),
        sa.Column("protein_g_per_portion", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_recipe_batches_session_id", "recipe_batches", ["session_id"])

    op.create_table(
        "portions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=UUID_DEFAULT),
        sa.Column(
            "batch_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("recipe_batches.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("calories", sa.Float(), nullable=False),
        sa.Column("protein_g", sa.Float(), nullable=False),
        sa.Column("estimated", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("state", item_state, nullable=False, server_default="PREPARED"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_portions_batch_id", "portions", ["batch_id"])
    op.create_index("ix_portions_user_id", "portions", ["user_id"])

    op.create_table(
        "meal_logs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, server_default=UUID_DEFAULT),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "portion_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("portions.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("calories_at_log", sa.Float(), nullable=False),
        sa.Column("protein_g_at_log", sa.Float(), nullable=False),
        sa.Column("estimated", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("logged_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("voided", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_meal_logs_user_id", "meal_logs", ["user_id"])

    # REQ-6.4 idempotency: one *active* log per portion. Saying "I ate one"
    # twice hits this constraint; the application catches it and returns
    # ALREADY_CONSUMED. Voiding a log frees the portion to be logged again,
    # which is what makes correction-by-voice work without an undo button.
    op.create_index(
        "uq_meal_logs_active_portion",
        "meal_logs",
        ["portion_id"],
        unique=True,
        postgresql_where=sa.text("voided = false"),
    )


def downgrade() -> None:
    op.drop_index("uq_meal_logs_active_portion", table_name="meal_logs")
    op.drop_index("ix_meal_logs_user_id", table_name="meal_logs")
    op.drop_table("meal_logs")

    op.drop_index("ix_portions_user_id", table_name="portions")
    op.drop_index("ix_portions_batch_id", table_name="portions")
    op.drop_table("portions")

    op.drop_index("ix_recipe_batches_session_id", table_name="recipe_batches")
    op.drop_table("recipe_batches")

    op.drop_index("ix_session_ingredients_session_id", table_name="session_ingredients")
    op.drop_table("session_ingredients")

    op.drop_index("ix_cooking_sessions_user_id", table_name="cooking_sessions")
    op.drop_table("cooking_sessions")

    op.drop_index("ix_pantry_items_user_id", table_name="pantry_items")
    op.drop_table("pantry_items")

    op.drop_index("ix_preferences_user_id", table_name="preferences")
    op.drop_table("preferences")

    op.drop_index("ix_equipment_user_id", table_name="equipment")
    op.drop_table("equipment")

    op.drop_table("profiles")
    op.drop_table("users")

    bind = op.get_bind()
    nutrition_source.drop(bind, checkfirst=True)
    session_status.drop(bind, checkfirst=True)
    item_state.drop(bind, checkfirst=True)
